overblog_graphql:
    definitions:
        schema:
            mutation: RootMutation
            query: RootQuery
        mappings:
            types:
                -
                    type: yaml
                    dir: "%kernel.project_dir%/config/graphql/types"
                    suffix: null
